version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:latest

    container_name: breedbase_web_milkweed
    ports:
      - 8101:8080
    volumes:
      - type: bind
        source: /export/prod/public_milkweed
        target: /home/production/public
      - type: bind
        source: /export/prod/public_milkweed/milkweed_blastdbs
        target: /home/production/blast
      - type: bind
        source: sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: db_dumps
        target: /db_dumps
      - type: bind
        source: bash_history
        target: /home/production/.bash_history
volumes:
  webdata:
  dbdata:



